# Generated by Django 3.1.6 on 2021-02-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='会社名')),
                ('date', models.DateField(verbose_name='年月日')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roa', models.CharField(max_length=255, verbose_name='ROA')),
                ('roe', models.CharField(max_length=255, verbose_name='ROE')),
                ('gross_profit_margin', models.CharField(max_length=255, verbose_name='売上高総利益率')),
                ('operating_income_margin', models.CharField(max_length=255, verbose_name='売上高営業利益率')),
                ('ordinary_rate_of_return_on_sales', models.CharField(max_length=255, verbose_name='売上高経常利益率')),
                ('sg_and_a_interest_ate_on_sales', models.CharField(max_length=255, verbose_name='売上高販売管理費利率')),
                ('current_ratio', models.CharField(max_length=255, verbose_name='流動比率')),
                ('quick_ratio', models.CharField(max_length=255, verbose_name='当座比率')),
                ('debt_ratio', models.CharField(max_length=255, verbose_name='負債比率')),
                ('capital_adequacy_ratio', models.CharField(max_length=255, verbose_name='自己資本比率')),
                ('sales_growth_rate', models.CharField(max_length=255, verbose_name='売上高増加率')),
                ('profit_growth_rate', models.CharField(max_length=255, verbose_name='利益増加率')),
                ('total_capital_increase_rate', models.CharField(max_length=255, verbose_name='総資本増加率')),
                ('net_asset_growth_rate', models.CharField(max_length=255, verbose_name='純資産増加率')),
                ('employee_growth_rate', models.CharField(max_length=255, verbose_name='従業員増加率')),
                ('total_asset_turnover', models.CharField(max_length=255, verbose_name='総資本回転率')),
                ('fixed_asset_turnover_rate', models.CharField(max_length=255, verbose_name='固定資産回転率')),
                ('inventories_turnover', models.CharField(max_length=255, verbose_name='棚卸資産回転率')),
                ('company', models.ManyToManyField(to='corporateanalysis.Company', verbose_name='会社')),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
